owner: constructions-incongrues
repo: institut-status

sites:
  - name: Institut
    url: https://institut.incongru.org
  - name: Ivresse
    url: https://data.constructions-incongrues.net/musiques-incongrues/
  - name: Tentacules
    url: https://tentacules.interzone.network
  - name: Yazoo!
    url: https://yazoo.constructions-incongrues.net/health

status-website:
  baseUrl: /institut-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Institut National de l'Incongru
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
